### ISSUE TITLE
RealSR dataset size

### ISSUE THREAD

**Issue by liqilei** [xiezw5/Component-Divide-and-Conquer-for-Real-World-Image-Super-Resolution#6]
Hi, I noticed that in RealSR dataset, for an image pair, the LR size and HR size are same. So, I wonder how you addressed this problem when training your network?

**Comment by xiezw5** [comment]
RealSR dataset provides the extended version in which LR and HR have different resolution. You can find them in their github.

**Comment by liqilei** [comment]
> RealSR dataset provides the extended version in which LR and HR have different resolution. You can find them in their github.

Sure, thanks.
