### ISSUE TITLE
the resolution of images in the testing set and the training set is not consistent.

### ISSUE THREAD

**Issue by junxiao01** [xiezw5/Component-Divide-and-Conquer-for-Real-World-Image-Super-Resolution#8]
I found that the resolution of HR images and LR images in the testing set is the same, but the resolution of HR images and LR images in the training set is not.  How do you perform inference in such a testing test? Or have you applied any post-processing techniques to the testing set?

**Comment by reddandelion217** [comment]
which scale did you mention about?for x2, the resolution of HR and LR is different for both test and train.

**Comment by junxiao01** [comment]
sorry, I made the mistake when I implemented the data processing script of my program.
