### ISSUE TITLE
Where I can find the supplementary file?

### ISSUE THREAD

**Issue by Fcsalvagnini** [xiezw5/Component-Divide-and-Conquer-for-Real-World-Image-Super-Resolution#9]
Hey guys, I'm searching for the supplementary material where you provide more details about dataset construction, but I can't find it. Can you please share it with me?

**Comment by karimdaou** [comment]
Here is the link: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123530103-supp.zip
